### ISSUE TITLE
pandas error

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [sejmodha/MiscScripts#6]
Thanks for the script, but getting this error:

 updatekrakendb.py
/media/disk1_12TB/tallnut/db/kraken2/refseq
/media/disk1_12TB/tallnut/db/kraken2/refseq
Downloading human genome

--2021-02-18 10:07:12--  ftp://ftp.ncbi.nih.gov/genomes/refseq/assembly_summary_refseq.txt
           => ‘assembly_summary_refseq.txt’
Resolving ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)... 165.112.9.228, 2607:f220:41e:250::11, 2607:f220:41e:250::13, ...
Connecting to ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)|165.112.9.228|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /genomes/refseq ... done.
==> SIZE assembly_summary_refseq.txt ... 66360144
==> PASV ... done.    ==> RETR assembly_summary_refseq.txt ... done.
Length: 66360144 (63M) (unauthoritative)

assembly_summary_refseq.txt                   100%[=================================================================================================>]  68.47M  1.13MB/s    in 97s

2021-02-18 10:08:54 (724 KB/s) - ‘assembly_summary_refseq.txt’ saved [71801632]

/home/tallnutt/d/scripts/updatekrakendb.py:81: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  assembly_sum = pd.read_table('assembly_summary_refseq.txt',dtype='unicode')
Traceback (most recent call last):
  File "/home/tallnutt/d/scripts/updatekrakendb.py", line 116, in <module>
    download_refseq_genome(9606,'human_genome_url.txt')
  File "/home/tallnutt/d/scripts/updatekrakendb.py", line 81, in download_refseq_genome
    assembly_sum = pd.read_table('assembly_summary_refseq.txt',dtype='unicode')
  File "/opt/miniconda3/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/miniconda3/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 435, in _read
    data = parser.read(nrows)
  File "/opt/miniconda3/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1139, in read
    ret = self._engine.read(nrows)
  File "/opt/miniconda3/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1995, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 968, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 955, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2172, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 22 fields in line 141712, saw 36

**Comment by mramirezs** [comment]
I have the same issue, please help!

**Comment by sejmodha** [comment]
Hi Both,

I have updated the `read_table` function to `read_csv` but not sure if it would fix the problem you are both facing. 
Can you please download the most recent version of the script and let me know if it works now.

PS: I am not working on this project anymore so it may take a little longer to fix any future errors related to this. Apologies for the late reply.

Thanks
